CREATE TABLE USER
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) UNIQUE,
    REGISTERDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ROOMCONDITION
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAME VARCHAR(20) NOT NULL,
    CONSTRAINT ROOMCONDITION_NAME
        FOREIGN KEY (NAME) REFERENCES USER (NAME)
        ON UPDATE CASCADE
);

CREATE TABLE HUMANCONDITION
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HEART FLOAT,
    STEPS INT,
    DISTANCE FLOAT,
    CALORIES INT,
    TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAME VARCHAR(20) NOT NULL,
    CONSTRAINT HUMANCONDITION_NAME
        FOREIGN KEY (NAME) REFERENCES USER (NAME)
        ON UPDATE CASCADE
);

CREATE TABLE HUMANCONDITION_SLEEP
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SLEEP FLOAT,
    TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAME VARCHAR(20) NOT NULL,
    CONSTRAINT HUMANCONDITION_SLEEP_NAME
        FOREIGN KEY (NAME) REFERENCES USER (NAME)
        ON UPDATE CASCADE
);
